# PlayCY Plugin | Version: 1.0 | Chuan Yeow
# No one else can Use this Plugin except for PlayCY!

# Spawn
Spawn:
    World: PlayCY_Spawn
    x: -1342.58
    y: 70.00
    z: 462.43
ArenaWorlds:
    Game1: Nukes01
    Game1Max: 20

    Game2: Nukes02
    Game2Max: 20

    Game3: Nukes03
    Game3Max: 20

    Game4: Nukes04
    Game4Max: 20

    Game5: Nukes05
    Game5Max: 20
Compass:
    Name: 'Game Menu'
HidePlayers:
    Name: 'Toggle Players'
News:
    Line 1: 'bcd'
    Line 2: 'bc'
    Line 3: 'bc'
    Line 4: 'bc'
    Line 5: 'bc'
    Line 6: 'bc'
ServerIF:
    Line 1: 'abc'
    Line 2: 'abc'
    Line 3: 'abc'
    Line 4: 'abc'
    Line 5: 'abc'
    Line 6: 'abc'
    Line 7: 'abc'
    Line 8: 'abc'
    Line 9: 'abc'
    Line 10: 'abc'
ServerHP:
    Line 1: 'abc'
    Line 2: 'abc'
    Line 3: 'abc'
    Line 4: 'abc'
    Line 5: 'abc'
    Line 6: 'abc'
    Line 7: 'abc'
    Line 8: 'abc'
    Line 9: 'abc'
    Line 10: 'abc'